#!/bin/bash

set -e

MIN_IOS_VERSION=13

export CMAKE_FLAGS="$CMAKE_FLAGS -DCMAKE_SYSTEM_NAME=iOS -DCMAKE_OSX_DEPLOYMENT_TARGET=$MIN_IOS_VERSION -DCMAKE_XCODE_ATTRIBUTE_IPHONEOS_DEPLOYMENT_TARGET=$MIN_IOS_VERSION -G Xcode"

./build.sh
