find_package(Boost 1.65.0 COMPONENTS multiprecision iostreams python numpy)
find_package(Python3 REQUIRED COMPONENTS Development Interpreter Development.Module Development.Embed Development.SABIModule)
add(python_unittest Python3::Python Boost::python Boost::numpy)
if (TARGET python_unittest)
  get_target_property(python_unittest_target_type python_unittest TYPE)
  if (python_unittest STREQUAL "MODULE_LIBRARY")
    target_compile_definitions(python_unittest PRIVATE MODULE_LIBRARY)
  endif ()
endif()
